# Generated by Django 2.2.2 on 2021-05-18 15:08

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitule',
            name='duration',
        ),
        migrations.AlterField(
            model_name='season',
            name='presentation',
            field=models.ImageField(upload_to=movies.models.upload_image_season, verbose_name='Portada'),
        ),
    ]
