# Generated by Django 2.2.2 on 2021-05-29 01:02

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210518_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitule',
            name='presentation',
            field=models.ImageField(upload_to=movies.models.upload_capitule),
        ),
    ]
